apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-backend-deployment
  labels:
    app: weatherapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: mamjo/weather:api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: json-configmap
          mountPath: /app/config
      volumes:
        - name: json-configmap
          configMap:
            name: backendConfig

