apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weather-app-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`darwin.moshiri.nl`)
    services:
    - kind: Service
      name: ui-service
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weather-backend-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - kind: Rule
    match: Host(`api.moshiri.nl`)
    services:
    - kind: Service
      name: api-service
      port: 80