apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: weatherui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: weatherapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80