name: Docker Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mamjo
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfileUi
          push: true
          tags:  mamjo/weather:ui

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfileApi
          push: true
          tags:  mamjo/weather:api
  

  deploy-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.MA_KUBE_CONFIG }}

      - name: Install Helm chart
        run: |
          helm install weatherapp /helm/weatherapp
