name: Deploy Helm Chart

on:
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.0.2'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.MA_KUBE_CONFIG }}

      - name: Install Helm chart
        run: |
          helm install weatherapp /helm/weatherapp
