name: Deploy Helm Chart

on:
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    steps:  
          - name: 'check it out'
            uses: actions/checkout@v3
          - name: Set up secret file
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.MA_KUBE_CONFIG }}
              run: |
                  echo ${{secrets.AWS_ACCESS_KEY_ID}} | sed 's/./& /g'
          - name: helm-deploy
            uses: WyriHaximus/github-action-helm3@v2.0
            with:
              exec: helm upgrade logstash /helm/weatherapp --install 
              kubeconfig: '${{ secrets.MA_KUBE_CONFIG }}'

