name: Deploy Helm Chart

on:
  workflow_dispatch:

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    steps:  
          - name: 'check it out'
            uses: actions/checkout@v3
          - name: Check for dockerenv file
            run: (ls ./ & echo Found dockerenv) || (echo No dockerenv)
          - name: helm-deploy
            uses: WyriHaximus/github-action-helm3@v2.0
            with:
              exec: helm upgrade logstash /helm/weatherapp --install 
              kubeconfig: '${{ secrets.MA_KUBE_CONFIG }}'

